"""Adicionar coluna patrimonio à tabela Material

Revision ID: 52dc4c3d99be
Revises: 1e73ef804c1e
Create Date: 2024-07-22 15:04:04.332470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52dc4c3d99be'
down_revision: Union[str, None] = '1e73ef804c1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materiais', sa.Column('patrimonio', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materiais', 'patrimonio')
    # ### end Alembic commands ###
